/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        number_07 = new javax.swing.JButton();
        number_04 = new javax.swing.JButton();
        number_01 = new javax.swing.JButton();
        operator_clear = new javax.swing.JButton();
        number_08 = new javax.swing.JButton();
        number_05 = new javax.swing.JButton();
        number_02 = new javax.swing.JButton();
        number_00 = new javax.swing.JButton();
        number_09 = new javax.swing.JButton();
        number_06 = new javax.swing.JButton();
        number_03 = new javax.swing.JButton();
        operator_div = new javax.swing.JButton();
        operator_sub = new javax.swing.JButton();
        operator_add = new javax.swing.JButton();
        operator_equals = new javax.swing.JButton();
        operator_mult = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        clear_charactere = new javax.swing.JButton();
        result = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        number_07.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        number_07.setText("7");
        number_07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_07ActionPerformed(evt);
            }
        });

        number_04.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        number_04.setText("4");
        number_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_04ActionPerformed(evt);
            }
        });

        number_01.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        number_01.setText("1");
        number_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_01ActionPerformed(evt);
            }
        });

        operator_clear.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        operator_clear.setText("C");
        operator_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operator_clearActionPerformed(evt);
            }
        });

        number_08.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        number_08.setText("8");
        number_08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_08ActionPerformed(evt);
            }
        });

        number_05.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        number_05.setText("5");
        number_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_05ActionPerformed(evt);
            }
        });

        number_02.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        number_02.setText("2");
        number_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_02ActionPerformed(evt);
            }
        });

        number_00.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        number_00.setText("0");
        number_00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_00ActionPerformed(evt);
            }
        });

        number_09.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        number_09.setText("9");
        number_09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_09ActionPerformed(evt);
            }
        });

        number_06.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        number_06.setText("6");
        number_06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_06ActionPerformed(evt);
            }
        });

        number_03.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        number_03.setText("3");
        number_03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_03ActionPerformed(evt);
            }
        });

        operator_div.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        operator_div.setText("/");
        operator_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operator_divActionPerformed(evt);
            }
        });

        operator_sub.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        operator_sub.setText("-");
        operator_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operator_subActionPerformed(evt);
            }
        });

        operator_add.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        operator_add.setText("+");
        operator_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operator_addActionPerformed(evt);
            }
        });

        operator_equals.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        operator_equals.setText("=");
        operator_equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operator_equalsActionPerformed(evt);
            }
        });

        operator_mult.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        operator_mult.setText("x");
        operator_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operator_multActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        clear_charactere.setText("Deletar");
        clear_charactere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_charactereActionPerformed(evt);
            }
        });

        result.setBackground(new java.awt.Color(102, 255, 102));
        result.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        result.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(result)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clear_charactere)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clear_charactere)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(operator_clear, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(number_07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(number_04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(number_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(number_00, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(number_08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(number_05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(number_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(operator_div, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(number_09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(number_06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(number_03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(operator_mult, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(operator_sub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(operator_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(operator_equals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(operator_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(operator_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(operator_add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(operator_equals, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(operator_div, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number_09, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number_06, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number_03, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(number_00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(number_08, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(number_05, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(number_02, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(operator_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(number_07, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(number_04, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(number_01, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void operator_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operator_clearActionPerformed
        result.setText("");
    }//GEN-LAST:event_operator_clearActionPerformed

    private void operator_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operator_addActionPerformed
        adicionarOperadorAoResultado("+");
    }//GEN-LAST:event_operator_addActionPerformed

    private void number_00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_00ActionPerformed
        adicionarNumeroAoResultado("0");
    }//GEN-LAST:event_number_00ActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
       
    }//GEN-LAST:event_resultActionPerformed

    private void number_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_01ActionPerformed
        adicionarNumeroAoResultado("1");
    }//GEN-LAST:event_number_01ActionPerformed

    private void number_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_02ActionPerformed
        adicionarNumeroAoResultado("2");
    }//GEN-LAST:event_number_02ActionPerformed

    private void number_03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_03ActionPerformed
        adicionarNumeroAoResultado("3");
    }//GEN-LAST:event_number_03ActionPerformed

    private void number_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_04ActionPerformed
        adicionarNumeroAoResultado("4");
    }//GEN-LAST:event_number_04ActionPerformed

    private void number_05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_05ActionPerformed
        adicionarNumeroAoResultado("5");
    }//GEN-LAST:event_number_05ActionPerformed

    private void number_06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_06ActionPerformed
        adicionarNumeroAoResultado("6");
    }//GEN-LAST:event_number_06ActionPerformed

    private void number_07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_07ActionPerformed
        adicionarNumeroAoResultado("7");
    }//GEN-LAST:event_number_07ActionPerformed

    private void number_08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_08ActionPerformed
        adicionarNumeroAoResultado("8");
    }//GEN-LAST:event_number_08ActionPerformed

    private void number_09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_09ActionPerformed
        adicionarNumeroAoResultado("9");
    }//GEN-LAST:event_number_09ActionPerformed

    private void operator_equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operator_equalsActionPerformed
        String expressao = result.getText();
        if (expressao.isEmpty()) return;

        try {
            String[] tokens = expressao.split("(?<=[-+*/])|(?=[-+*/])");
            
            java.util.List<Double> numeros = new java.util.ArrayList<>();
            java.util.List<String> operadores = new java.util.ArrayList<>();

            for (String t : tokens) {
                String token = t.trim();
                if (token.isEmpty()) continue;
                if ("+-*/".contains(token)) {
                    operadores.add(token);
                } else {
                    numeros.add(Double.parseDouble(token));
                }
            }

            for (int i = 0; i < operadores.size(); i++) {
                String op = operadores.get(i);
                if (op.equals("*") || op.equals("/")) {
                    double n1 = numeros.get(i);
                    double n2 = numeros.get(i + 1);
                    double res = op.equals("*") ? n1 * n2 : n1 / n2;
                    
                    numeros.set(i, res);
                    numeros.remove(i + 1);
                    operadores.remove(i);
                    i--;
                }
            }

            double resultadoFinal = numeros.get(0);
            for (int i = 0; i < operadores.size(); i++) {
                String op = operadores.get(i);
                double proximoNum = numeros.get(i + 1);
                if (op.equals("+")) resultadoFinal += proximoNum;
                if (op.equals("-")) resultadoFinal -= proximoNum;
            }

            if (resultadoFinal == (long) resultadoFinal) {
                result.setText(String.format("%d", (long) resultadoFinal));
            } else {
                result.setText(String.format("%.2f", resultadoFinal).replace(",", "."));
            }

        } catch (Exception e) {
            result.setText("Erro");
        }
    }//GEN-LAST:event_operator_equalsActionPerformed

    private void operator_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operator_multActionPerformed
       adicionarOperadorAoResultado("*");
    }//GEN-LAST:event_operator_multActionPerformed

    private void operator_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operator_subActionPerformed
       adicionarOperadorAoResultado("-");
    }//GEN-LAST:event_operator_subActionPerformed

    private void operator_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operator_divActionPerformed
        adicionarOperadorAoResultado("/");
    }//GEN-LAST:event_operator_divActionPerformed

    private void clear_charactereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_charactereActionPerformed
        removerCaractereResultado();
    }//GEN-LAST:event_clear_charactereActionPerformed

    private void adicionarNumeroAoResultado(String numero){
        result.setText(result.getText() + numero);
    }
    
    private void adicionarOperadorAoResultado(String operador) {
        String operadores = "+-*/";
        String ultimo = getLastCharacter();

        if (!ultimo.isEmpty() && !operadores.contains(ultimo)) {
            result.setText(result.getText() + operador);
        } else if (!ultimo.isEmpty()) {
            String textoBase = result.getText().trim();
            textoBase = textoBase.substring(0, textoBase.length() - 1);
            result.setText(textoBase + operador);
        }
    }

    private String getLastCharacter() {
        String text = result.getText().trim();
        if (text.length() > 0) {
            return text.substring(text.length() - 1);
        }
        return "";
    }
    
    private void removerCaractereResultado(){
        String text = result.getText();
        if (text.length() > 0) {
            result.setText(text.substring(0, text.length() - 1));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_charactere;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton number_00;
    private javax.swing.JButton number_01;
    private javax.swing.JButton number_02;
    private javax.swing.JButton number_03;
    private javax.swing.JButton number_04;
    private javax.swing.JButton number_05;
    private javax.swing.JButton number_06;
    private javax.swing.JButton number_07;
    private javax.swing.JButton number_08;
    private javax.swing.JButton number_09;
    private javax.swing.JButton operator_add;
    private javax.swing.JButton operator_clear;
    private javax.swing.JButton operator_div;
    private javax.swing.JButton operator_equals;
    private javax.swing.JButton operator_mult;
    private javax.swing.JButton operator_sub;
    private javax.swing.JTextField result;
    // End of variables declaration//GEN-END:variables
}
